### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Asslam** [lightbase/cacic#5]
Tenho o seguinte erro ao tentar cadastrar Computadores e Subrede.
Por favor ajudem-me.

An exception occurred while executing '
select c.id_computador,
c.te_ip_computador,
r.te_mascara_rede,
(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text) as cidr_bits,
r.te_ip_rede as rede_velha,
r.id_rede,
host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet)) as rede_nova,
(SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) as id_rede2
from computador c
inner join rede r on c.id_rede = r.id_rede
where c.te_ip_computador is not null
and (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) is not null
and (c.ativo IS NULL or c.ativo = 't')
order by rede_nova;
':

SQLSTATE[42883]: Undefined function: 7 ERROR: function inet_to_longip(inet) does not exist
LINE 5: (netmask_bits(inet_to_longip(r.te_mascara_rede::inet)...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
500 Internal Server Error - DBALException
1 linked Exception:

    PDOException »

[2/2] DBALException: An exception occurred while executing '
select c.id_computador,
c.te_ip_computador,
r.te_mascara_rede,
(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text) as cidr_bits,
r.te_ip_rede as rede_velha,
r.id_rede,
host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet)) as rede_nova,
(SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) as id_rede2
from computador c
inner join rede r on c.id_rede = r.id_rede
where c.te_ip_computador is not null
and (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) is not null
and (c.ativo IS NULL or c.ativo = 't')
order by rede_nova;
':

SQLSTATE[42883]: Undefined function: 7 ERROR: function inet_to_longip(inet) does not exist
LINE 5: (netmask_bits(inet_to_longip(r.te_mascara_rede::inet)...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.  +
[1/2] PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR: function inet_to_longip(inet) does not exist
LINE 5: (netmask_bits(inet_to_longip(r.te_mascara_rede::inet)...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.  +
Logs  -
1 error

    INFO - Matched route "cacic_subrede_computadores" (parameters: "_controller": "Cacic\CommonBundle\Controller\RedeController::computadoresAction", "_route": "cacic_subrede_computadores")
    DEBUG - Read SecurityContext from the session
    DEBUG - Reloading user from user provider.
    DEBUG - SELECT t0.id_usuario AS id_usuario1, t0.id_usuario_ldap AS id_usuario_ldap2, t0.nm_usuario_acesso AS nm_usuario_acesso3, t0.nm_usuario_completo AS nm_usuario_completo4, t0.nm_usuario_completo_ldap AS nm_usuario_completo_ldap5, t0.te_senha AS te_senha6, t0.dt_log_in AS dt_log_in7, t0.te_emails_contato AS te_emails_contato8, t0.te_telefones_contato AS te_telefones_contato9, t0.api_key AS api_key10, t0.crypt_key AS crypt_key11, t0.is_active AS is_active12, t0.id_local AS id_local13, t0.id_servidor_autenticacao AS id_servidor_autenticacao14, t0.id_grupo_usuario AS id_grupo_usuario15 FROM usuario t0 WHERE t0.id_usuario = ?
    DEBUG - Username "admin" was reloaded from user provider.
    DEBUG - SELECT t0.id_grupo_usuario AS id_grupo_usuario1, t0.nm_grupo_usuarios AS nm_grupo_usuarios2, t0.te_grupo_usuarios AS te_grupo_usuarios3, t0.te_menu_grupo AS te_menu_grupo4, t0.te_descricao_grupo AS te_descricao_grupo5, t0.cs_nivel_administracao AS cs_nivel_administracao6, t0.role AS role7 FROM grupo_usuario t0 WHERE t0.id_grupo_usuario = ?
    INFO - No expression found; abstaining from voting.
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\PaginatorBundle\Subscriber\SlidingPaginationSubscriber::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".
    DEBUG - select c.id_computador, c.te_ip_computador, r.te_mascara_rede, (netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text) as cidr_bits, r.te_ip_rede as rede_velha, r.id_rede, host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet)) as rede_nova, (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) as id_rede2 from computador c inner join rede r on c.id_rede = r.id_rede where c.te_ip_computador is not null and (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) is not null and (c.ativo IS NULL or c.ativo = 't') order by rede_nova;
    CRITICAL - Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing ' select c.id_computador, c.te_ip_computador, r.te_mascara_rede, (netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text) as cidr_bits, r.te_ip_rede as rede_velha, r.id_rede, host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet)) as rede_nova, (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) as id_rede2 from computador c inner join rede r on c.id_rede = r.id_rede where c.te_ip_computador is not null and (SELECT id_rede FROM rede WHERE te_ip_rede = host(network((c.te_ip_computador||'/'||(netmask_bits(inet_to_longip(r.te_mascara_rede::inet))::text))::inet))) is not null and (c.ativo IS NULL or c.ativo = 't') order by rede_nova; ': SQLSTATE[42883]: Undefined function: 7 ERROR: function inet_to_longip(inet) does not exist LINE 5: (netmask_bits(inet_to_longip(r.te_mascara_rede::inet)... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts." at /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ErrorsLoggerListener::injectLogger".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\SessionListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Component\Security\Http\Firewall::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Symfony\Bundle\AsseticBundle\EventListener\RequestListener::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\PaginatorBundle\Subscriber\SlidingPaginationSubscriber::onKernelRequest".
    DEBUG - Notified event "kernel.request" to listener "Knp\Bundle\MenuBundle\EventListener\VoterInitializerListener::onKernelRequest".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener::onKernelController".
    DEBUG - Notified event "kernel.controller" to listener "Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener::onKernelController".

Stack Trace (Plain Text)  +
Symfony 2.5.7
PHP
Environment 8c9e72
Request 500 RedeController computadoresAction
Logs 1
Time 242 ms
Memory Usage 9.5 MB
Forms 0
Security
a

**Comment by eduardosan** [comment]
Olá,

Essa função é criada num dos migrations executados pelo sistema. Execute o seguinte comando:

<pre>
php app/console doctrine:migrations:migrate
</pre>

Isso deve resolver a questão.

**Comment by Asslam** [comment]
Obrigado, executei o comando conforme o descrito.

No fim deu a seguinte mensagem:
PHP Fatal error: Call to a member funtion getTeServUpdates () on a non-object in /srv/cacic/src/Cacic/CommonBundle/DoctrineMigrations/Version20150213142949.php on line 50


Quando executo
Cadastro>Computadores e Subredes a mensagem:

DataTables warning (table id = 'datatable'): Requested umknown parameter '1' from the data source for row 0

**Comment by eduardosan** [comment]
Prezado,

Pode informar qual o procedimento de instalação que você seguiu? Trata-se de uma nova instalação ou atualização?

É necessário executar o seguinte comando descrito no manual:

<pre>
php app/console doctrine:fixtures:load
</pre>

**Comment by Asslam** [comment]
Efectuei uma nova instalacao.

**Comment by eduardosan** [comment]
Para uma nova versão é necessário carregar os dados padrão do sistema, que é justamente o motivo dessa mensagem de erro que você está vendo. A execução do comando deve resolver a questão:

<pre>
php app/console doctrine:fixtures:load
</pre>

**Comment by Asslam** [comment]
Ola
Executei o comando 
php app/console doctrine:fixtures:load

Tive o seguinte resultado
Careful, database will be purged. Do you want to continue Y/N ?  cliquei em Y


O facto é que não consigo efectuar nenhum cadastro.

Cadastro>Subredes
 Erro:
 
 
 
 
 
 
An exception occurred while executing 'INSERT INTO rede (te_ip_rede, nm_rede, te_observacao, nm_pessoa_contato1, nm_pessoa_contato2, nu_telefone1, te_email_contato2, nu_telefone2, te_email_contato1, te_serv_cacic, te_serv_updates, te_path_serv_updates, nm_usuario_login_serv_updates, te_senha_login_serv_updates, nu_porta_serv_updates, te_mascara_rede, dt_verifica_updates, nm_usuario_login_serv_updates_gerente, te_senha_login_serv_updates_gerente, nu_limite_ftp, cs_permitir_desativar_srcacic, te_debugging, dt_debug, download_method, id_local, id_servidor_autenticacao) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["192.168.66.0", null, null, null, null, "", null, "", null, "http:\/\/localhost", "http:\/\/localhost", null, null, null, "21", "255.255.255.0", null, null, null, 100, null, null, null, null, 3, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "cs_permitir_desativar_srcacic" violates not-null constraint
DETAIL: Failing row contains (4, 3, null, 192.168.66.0, null, null, null, null, , null, , null, http://localhost, http://localhost, null, null, null, 21, 255.255.255.0, null, null, null, 100, null, null, null, null).
500 Internal Server Error -
1 linked Exception:
•	»
 
[2/2] : An exception occurred while executing 'INSERT INTO rede (te_ip_rede, nm_rede, te_observacao, nm_pessoa_contato1, nm_pessoa_contato2, nu_telefone1, te_email_contato2, nu_telefone2, te_email_contato1, te_serv_cacic, te_serv_updates, te_path_serv_updates, nm_usuario_login_serv_updates, te_senha_login_serv_updates, nu_porta_serv_updates, te_mascara_rede, dt_verifica_updates, nm_usuario_login_serv_updates_gerente, te_senha_login_serv_updates_gerente, nu_limite_ftp, cs_permitir_desativar_srcacic, te_debugging, dt_debug, download_method, id_local, id_servidor_autenticacao) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["192.168.66.0", null, null, null, null, "", null, "", null, "http:\/\/localhost", "http:\/\/localhost", null, null, null, "21", "255.255.255.0", null, null, null, 100, null, null, null, null, 3, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "cs_permitir_desativar_srcacic" violates not-null constraint
DETAIL: Failing row contains (4, 3, null, 192.168.66.0, null, null, null, null, , null, , null, http://localhost, http://localhost, null, null, null, 21, 255.255.255.0, null, null, null, 100, null, null, null, null).  
[1/2] : SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "cs_permitir_desativar_srcacic" violates not-null constraint
DETAIL: Failing row contains (4, 3, null, 192.168.66.0, null, null, null, null, , null, , null, http://localhost, http://localhost, null, null, null, 21, 255.255.255.0, null, null, null, 100, null, null, null, null).  
Logs   
1 error
Stack Trace (Plain Text)  
 
[1] Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO rede (te_ip_rede, nm_rede, te_observacao, nm_pessoa_contato1, nm_pessoa_contato2, nu_telefone1, te_email_contato2, nu_telefone2, te_email_contato1, te_serv_cacic, te_serv_updates, te_path_serv_updates, nm_usuario_login_serv_updates, te_senha_login_serv_updates, nu_porta_serv_updates, te_mascara_rede, dt_verifica_updates, nm_usuario_login_serv_updates_gerente, te_senha_login_serv_updates_gerente, nu_limite_ftp, cs_permitir_desativar_srcacic, te_debugging, dt_debug, download_method, id_local, id_servidor_autenticacao) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["192.168.66.0", null, null, null, null, "", null, "", null, "http:\/\/localhost", "http:\/\/localhost", null, null, null, "21", "255.255.255.0", null, null, null, 100, null, null, null, null, 3, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "cs_permitir_desativar_srcacic" violates not-null constraint
DETAIL:  Failing row contains (4, 3, null, 192.168.66.0, null, null, null, null, , null, , null, http://localhost, http://localhost, null, null, null, 21, 255.255.255.0, null, null, null, 100, null, null, null, null).
    at n/a
        in /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91

    at Doctrine\DBAL\DBALException::driverExceptionDuringQuery(object(PDOException), 'INSERT INTO rede (te_ip_rede, nm_rede, te_observacao, nm_pessoa_contato1, nm_pessoa_contato2, nu_telefone1, te_email_contato2, nu_telefone2, te_email_contato1, te_serv_cacic, te_serv_updates, te_path_serv_updates, nm_usuario_login_serv_updates, te_senha_login_serv_updates, nu_porta_serv_updates, te_mascara_rede, dt_verifica_updates, nm_usuario_login_serv_updates_gerente, te_senha_login_serv_updates_gerente, nu_limite_ftp, cs_permitir_desativar_srcacic, te_debugging, dt_debug, download_method, id_local, id_servidor_autenticacao) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array('192.168.66.0', null, null, null, null, '', null, '', null, 'http://localhost', 'http://localhost', null, null, null, '21', '255.255.255.0', null, null, null, '100', null, null, null, null, '3', null))
        in /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 167

    at Doctrine\DBAL\Statement->execute()
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php line 279

    at Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 966

    at Doctrine\ORM\UnitOfWork->executeInserts(object(ClassMetadata))
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 335

    at Doctrine\ORM\UnitOfWork->commit(null)
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php line 389

    at Doctrine\ORM\EntityManager->flush(null)
        in /srv/cacic/app/cache/dev/jms_diextra/doctrine/EntityManager_55859bc43a635.php line 402

    at EntityManager55859bc43a635_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->flush()
        in /srv/cacic/src/Cacic/CommonBundle/Controller/RedeController.php line 54

    at Cacic\CommonBundle\Controller\RedeController->cadastrarAction(object(Request))
        in  line

    at call_user_func_array(array(object(RedeController), 'cadastrarAction'), array(object(Request)))
        in /srv/cacic/app/bootstrap.php.cache line 2975

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /srv/cacic/app/bootstrap.php.cache line 2937

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /srv/cacic/app/bootstrap.php.cache line 3086

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /srv/cacic/app/bootstrap.php.cache line 2336

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /srv/cacic/web/app_dev.php line 27

[2] PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "cs_permitir_desativar_srcacic" violates not-null constraint
DETAIL:  Failing row contains (4, 3, null, 192.168.66.0, null, null, null, null, , null, , null, http://localhost, http://localhost, null, null, null, 21, 255.255.255.0, null, null, null, 100, null, null, null, null).
    at n/a
        in /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 165

    at PDOStatement->execute(null)
        in /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 165

    at Doctrine\DBAL\Statement->execute()
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php line 279

    at Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 966

    at Doctrine\ORM\UnitOfWork->executeInserts(object(ClassMetadata))
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 335

    at Doctrine\ORM\UnitOfWork->commit(null)
        in /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php line 389

    at Doctrine\ORM\EntityManager->flush(null)
        in /srv/cacic/app/cache/dev/jms_diextra/doctrine/EntityManager_55859bc43a635.php line 402

    at EntityManager55859bc43a635_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager->flush()
        in /srv/cacic/src/Cacic/CommonBundle/Controller/RedeController.php line 54

    at Cacic\CommonBundle\Controller\RedeController->cadastrarAction(object(Request))
        in  line

    at call_user_func_array(array(object(RedeController), 'cadastrarAction'), array(object(Request)))
        in /srv/cacic/app/bootstrap.php.cache line 2975

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /srv/cacic/app/bootstrap.php.cache line 2937

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /srv/cacic/app/bootstrap.php.cache line 3086

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /srv/cacic/app/bootstrap.php.cache line 2336

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /srv/cacic/web/app_dev.php line 27

**Comment by eduardosan** [comment]
@Asslam 

Obrigado pela dica. Desculpe, mas o release publicado continha um erro grave que impedia o cadastro das subredes. Acabei de corrigir o release e republiquei a versão 3.1.15.

Você pode baixar novamente o código, por favor? Depois execute a instalação e o schema update novamente.

<pre>
php composer.phar install
php app/console doctrine:schema:update --force
php app/console cache:clear --env=prod
</pre>

Isso deve ser suficiente para resolver o problema.

Desculpe o incômodo e obrigado pela dica. Se estiver resolvido, lembre-se de fechar a issue.

**Comment by eduardosan** [comment]
Ah, desculpe, mas será necessário executar também o seguinte comando:

<pre>
php app/console doctrine:migrations:migrate
</pre>

**Comment by Asslam** [comment]
onde encontro a republicação da versão 3.1.15, para eu baixar o código?

**Comment by eduardosan** [comment]
No mesmo endereço da versão anterior:

https://github.com/lightbase/cacic/archive/v3.1.15.tar.gz

**Comment by Asslam** [comment]
Na instalação que fiz, usei o tutorial de instalação manual no ubuntu com o comando
# git clone https://github.com/lightbase/cacic
poço usar o mesmo camando?

**Comment by eduardosan** [comment]
Pode sim. É só dar um git pull.

**Comment by aldomarjunior** [comment]
Boa Noite Eduardo.
estou com o mesmo problema e como não teve continuidade neste resolvi dar continuidade.
Quando executo o comando   php app/console doctrine:schema:update --force  tenho o seguinte erro no console

php app/console doctrine:schema:update --force
Updating database schema...

  [Doctrine\DBAL\DBALException]                                                         
  An exception occurred while executing 'DROP INDEX IDX_9BBDD0F89F1B3279':              
  SQLSTATE[42704]: Undefined object: 7 ERRO:  índice "idx_9bbdd0f89f1b3279" não existe  
                                                                                        
  [PDOException]                                                                        
  SQLSTATE[42704]: Undefined object: 7 ERRO:  índice "idx_9bbdd0f89f1b3279" não existe  
                                                                                        
doctrine:schema:update [--complete] [--dump-sql] [--force] [--em[="..."]]

Ps: executei os passos indicados por vc neste post, porem esta dando esse erro.

Fiz toda a instalação do zero utilizando o Debian e a versão estavel 3.1.15 (essa que vc publicou aqui no post) e toda a instalação correu sem problemas e sem erros, porem quando vou instalar o agente ele não realiza os downloads necessarios para a instalação. Pesquisando chegei a resposta de que me parece que o problema esta exatamente na falta do driver DBAL 

CRITICAL - Uncaught PHP Exception PDOException: "could not find driver" at /srv/cacic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 40

como devo proceder para corrigir este erro do driver?

**Comment by eduardosan** [comment]
Aldomar,

Aqui no github tratamos os erros do código. Para dúvidas sobre instalação o melhor canal é a comunidade:

https://portal.softwarepublico.gov.br/social/cacic

Esse erro significa que o procedimento de instalação não foi realizado com sucesso. Verifique novamente se instalou tudo e fique atento às mensagens de erro.
