### ISSUE TITLE
Erro Cocar? 

### ISSUE THREAD

**Issue by Daniel-Furcht** [lightbase/cacic#6]
Erro obtido em testes.
Instalação sem problemas, erro acontece logo após autenticação no Symphony.

CRITICAL - Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 120 near 'CocarBundle:Computador': Error: Class 'Swpb\Bundle\CocarBundle\Entity\Computador' is not defined." at /srv/cacic/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63

**Comment by Daniel-Furcht** [comment]
Provavel relação com o erro, este é um mapping error encontrado.

Cacic\CommonBundle\Entity\Computador	
The field Cacic\CommonBundle\Entity\Computador#notifications is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Cacic\CommonBundle\Entity\Notifications#idComputador does not contain the required 'inversedBy=notifications' attribute.

**Comment by eduardosan** [comment]
@Daniel-Furcht Você baixou versão do head? Procure sempre uma release estável, e ainda estamos na 3.1.15.

Essa é uma alteração que fizemos na Sexta-feira, e ainda não foi testada exaustivamente.

**Comment by Daniel-Furcht** [comment]
Ola. Tranquilo, sei disso, só estou testando as alterações e espero poder ajudar nos testes.
Levantei a questão porque na b5 não havia este problema.
Att.
Daniel

**Comment by eduardosan** [comment]
Olá Daniel,

Obrigado pela dica. Agora estou numa semana terrível e não vai dar pra 
olhar isso, mas se você executar um schema:update deve resolver a questão.

Isso faz parte de uma novidade que já está presente nessa versão do 
Cacic: autodescoberta de computadores.

On 09-12-2015 10:57, Daniel Furcht wrote:
>
> Ola. Tranquilo, sei disso, só estou testando as alterações e espero 
> poder ajudar nos testes.
> Levantei a questão porque na b5 não havia este problema.
> Att.
> Daniel
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lightbase/cacic/issues/6#issuecomment-163221682>.
>

-- 
Eduardo Santos
Programador

http://twitter.com/eduardosan
http://eduardosan.com

**Comment by eduardosan** [comment]
Resolvido no último release.
