### ISSUE TITLE
Problema na instalação

### ISSUE THREAD

**Issue by vitorvasconcelos** [lightbase/cacic#7]
Eduardo,

Fiz a instalação conforme este tutorial: https://www.vivaolinux.com.br/artigo/Tutorial-de-instalacao-e-configuracao-do-CACIC-3115?pagina=2

Fiz tudo certo mas não estou conseguindo acessar a pagina na web

tentei nos endereços

https://localhost/cacic/app_dev.php
https://localhost/app_dev.php

e nada poderia me auxiliar

**Comment by salbury** [comment]
https://www.scribd.com/doc/298998540/CACIC-3-1-15

**Comment by eduardosan** [comment]
O tutorial de instalação se consiste somente no seguinte agora:

1 - Instale o vagrant
2 - Instale o virtualbox
3 - Execute o comando

<pre>
vagrant up
</pre>

Acesse o endereço http://localhost:8080
